

permalink: /:categories/:title/
paginate_path: 'page:num'
paginate:      nil

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: ""
comments: true


url:         http://andylaucn.github.io


